### ISSUE TITLE
Editor crash Ubuntu 22.04

### ISSUE THREAD

**Issue by nigec** [fireclawthefox/SceneEditor#17] opened 2022-06-22 15:07 UTC
I'm getting a crash as soon as I try to do something, ie save a scene, add a model
`$ python3 main.py
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)

[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
Assertion failed: node_gbv != nullptr at line 217 of built1.11/include/cullTraverserData.I
Assertion failed: node_gbv != nullptr at line 217 of built1.11/include/cullTraverserData.I
Try to save project after unhandled exception. Please restart the app to automatically load the exception save file!
:task(error): Exception occurred in PythonTask igLoop
Try to save project after unhandled exception. Please restart the app to automatically load the exception save file!
`

**Comment by fireclawthefox** [comment] 2022-06-23 06:00
Hm, sounds like something's off with your audio setup from what I see in the ALSOFT line. Somethings trying to get real-time priority but fails. I did not do anything special for audio yet, can you do a few things to help me find the source of this problem?

1. Send the editors log file right after the crash. The logs should be in ~/.SceneEditor/logs/
2. If possible, check if other Panda3D applications crash too
3. Provide more details about your setup. (Used version of Panda3D, OS kernel, any special configuration you've done that may affects this)

With those we should be able to track down the problem further and hopefully be able to fix it.

**Comment by fireclawthefox** [comment] 2022-08-28 10:48
@nigec are you still having this bug and are you still interested in getting it solved? If so, I'd need your feedback on my questions since I can't reproduce it on my own Ubuntu 22.04 system.

**Comment by fireclawthefox** [comment] 2022-10-26 07:45
Will close this as not reproducible.

If you encounter this bug again, feel free to reopen it with new details.

**Closed by fireclawthefox** 2022-10-26 07:45 UTC
